# Generated by Django 6.0.3 on 2026-03-10 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('expediente_general', models.FileField(blank=True, null=True, upload_to='expedientes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(max_length=50)),
                ('lote_numero', models.CharField(max_length=50)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enganche', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estatus_contrato', models.CharField(default='Activo', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='clientes.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('COMPLETO', 'Pago Completo'), ('ABONO', 'Abono/Parcial')], max_length=10)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('comentarios', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
