# Generated by Django 6.0.3 on 2026-03-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='registrado_por',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='expediente_general',
            new_name='expediente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_completo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='multa',
            old_name='fecha_aplicacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='capital_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pagos_atrasados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pagos_concluidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porc_ganancia',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porc_gastos_sueldos',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porc_reinversion',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porc_total',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porc_trabajador',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='multa',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multa',
            name='motivo',
            field=models.TextField(default='Mora de $15 por cada $1000'),
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_abono_capital', models.BooleanField(default=False)),
                ('es_pago_inconcluso', models.BooleanField(default=False)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='clientes.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
